
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import SessionWrapper from "@/components/SessionWrapper";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Get me A Chai - Fund your projects with Chai",
  icons: {
    icon: "/favicon.ico",
    shortcut: "/favicon.ico",
    apple: "/apple-touch-icon.png",
  },
  description: "Generated by Sahil",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en"
      data-arp="" >
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased text-white min-h-screen relative `}>

        <SessionWrapper>
          <Navbar />
          <div className=""> {/* min-h-[88.1vh]*/}
            <div className="absolute inset-0 -z-10 h-full w-full items-center px-5 py-24 [background:radial-gradient(125%_125%_at_50%_10%,#000_40%,#63e_100%)] text-white"></div>

            {children}
          </div>
          <Footer />
        </SessionWrapper>
      </body>
    </html>
  );
}
